apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary


helmCharts:
- name: cert-manager
  releaseName: my-cert-manager
  namespace: cert-manager
- name: prometheus-operator
  repo: https://charts.cloudposse.com/incubator
  version: 0.2.0
  releaseName: my-prometheus-operator
